### ISSUE TITLE
仓库Tag是否打错了，如图：

### ISSUE THREAD

**Issue by jadesouth** [SeasX/seas-logger#10]
![image](https://user-images.githubusercontent.com/22884699/48109586-0064cf80-e283-11e8-9f40-331cd3e15e9d.png)

感觉应该是1.1.1吧，composer安装可能会受到版本的影响。
@Neeke

**Comment by jadesouth** [comment]
@wujunze 大佬

**Comment by wujunze** [comment]
谢谢提醒  已经修正
